## Package import

In [2]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
import joblib

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [5]:
%cd /content/drive/MyDrive/AbDev

/content/drive/MyDrive/AbDev

In [6]:
!pip install -q condacolab
import condacolab
condacolab.install()

✨🍰✨ Everything looks OK!

## Read the SAPSCM.csv file from DeepSP

In [7]:
dataset_test = pd.read_csv('DeepSP_descriptors_anarci2_Abdev.csv')
dataset_test

,Name,SAP_pos_CDRH1,SAP_pos_CDRH2,SAP_pos_CDRH3,SAP_pos_CDRL1,SAP_pos_CDRL2,SAP_pos_CDRL3,SAP_pos_CDR,SAP_pos_Hv,SAP_pos_Lv,...,SCM_pos_CDRH1,SCM_pos_CDRH2,SCM_pos_CDRH3,SCM_pos_CDRL1,SCM_pos_CDRL2,SCM_pos_CDRL3,SCM_pos_CDR,SCM_pos_Hv,SCM_pos_Lv,SCM_pos_Fv
0,abituzumab,3.859764,4.345273,8.718716,2.148599,4.696163,6.794335,30.680004,45.527824,36.425133,...,33.356182,50.214880,58.551710,37.382200,99.530860,19.154770,301.265560,877.35376,1176.29030,2044.6433
1,abrilumab,3.417136,1.079907,1.828652,2.087438,2.402200,6.014892,17.925526,43.011524,31.231604,...,3.424593,-1.281652,7.433341,36.730270,8.360390,19.308480,67.659920,919.62100,941.50415,1849.1388
2,adalimumab,2.134783,2.524245,14.445071,1.904740,3.589351,3.172182,27.496794,58.417650,30.517650,...,3.183182,19.583357,29.513483,116.769500,41.759360,55.548267,263.838930,907.11304,1219.44450,2109.0886
3,alemtuzumab,2.272270,3.696255,5.040778,2.220291,2.762960,3.326095,20.664444,52.663430,32.287445,...,31.126842,109.974250,113.784380,59.374570,59.348290,156.546020,539.401300,1461.24170,1302.77050,2748.4575
4,alirocumab,2.335272,0.485208,5.749701,6.340402,2.478856,4.473296,23.008087,52.346256,43.460670,...,87.390930,30.730070,22.045889,163.355850,64.857000,19.051237,393.546330,1270.46520,966.63160,2228.1846
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
132,vedolizumab,2.809752,0.265223,11.760819,5.934891,2.963002,2.818470,27.306590,51.973350,51.453320,...,30.365030,-3.822329,4.026950,147.944060,50.612793,64.961990,289.120800,982.95140,1155.89610,2126.8452
133,veltuzumab,2.509693,4.151934,14.463856,3.159272,4.066860,2.541194,31.233425,43.669390,37.644170,...,34.895670,0.024304,39.568436,32.313793,35.552647,30.637224,166.967970,1078.54030,1059.88610,2115.0830
134,visilizumab,6.160062,3.600580,15.227443,2.185713,3.861778,2.654676,34.395943,57.106976,32.811314,...,100.690540,106.182350,75.532430,-2.440957,69.549660,18.262016,372.927860,1269.87840,1078.14230,2312.8726
135,zalutumumab,1.994143,5.136198,18.606033,0.970755,2.458154,5.581917,34.689407,63.186800,32.754875,...,29.383791,5.332729,43.206482,1.038679,2.665065,29.451338,108.277626,1160.79310,941.98390,2081.3745
136,zanolimumab,2.153244,0.199033,7.362045,1.881888,3.059788,6.385337,22.490260,60.044056,33.883950,...,74.142380,40.338560,39.777084,23.505670,26.258083,18.633228,213.245270,1210.54380,1129.12660,2317.1243

## Features Selection and Transformation

In [9]:
feature_ACSINS = dataset_test[['SAP_pos_CDRH1', 'SAP_pos_CDRL3', 'SCM_pos_CDRH1','SCM_neg_CDR']]
feature_AS = dataset_test[['SAP_pos_CDRH2','SCM_pos_CDRL2','SCM_pos_CDRL3','SCM_neg_CDRL3']]
feature_BVP = dataset_test[['SAP_pos_CDRH1','SAP_pos_CDRH3','SCM_pos_CDR','SCM_neg_CDRH3']]
feature_CIC = dataset_test[['SAP_pos_CDRL2', 'SAP_pos_CDRL3', 'SAP_pos_Lv','SCM_neg_CDR']]
feature_CSI = dataset_test[['SAP_pos_CDRL1', 'SAP_pos_Lv', 'SCM_pos_CDRH2','SCM_neg_CDRL2']]
feature_ELISA = dataset_test[['SAP_pos_CDRH3', 'SCM_pos_CDR','SCM_neg_CDR']]
feature_HIC = dataset_test[['SAP_pos_CDRL3', 'SAP_pos_CDR','SAP_pos_Hv','SCM_pos_CDRH3']]
feature_HEK = dataset_test[['SAP_pos_CDRH2','SAP_pos_CDRL3','SCM_pos_Lv','SCM_neg_Lv']]
feature_PSR = dataset_test[['SAP_pos_Lv', 'SCM_pos_CDRH2', 'SCM_neg_CDRL2']]
feature_SGAC = dataset_test[['SAP_pos_CDRH1', 'SAP_pos_CDRL3', 'SCM_neg_CDRH2','SCM_neg_Lv']]
feature_SMAC = dataset_test[['SAP_pos_CDR', 'SAP_pos_Fv', 'SCM_neg_CDRL2','SCM_neg_Fv']]
feature_Tm = dataset_test[['SAP_pos_CDRH1', 'SAP_pos_CDRH2', 'SCM_pos_CDRH3']]

In [10]:
ACSINS_Scaler = joblib.load('Trained_model/scalers/scaler_ACSINS.joblib')
AS_Scaler = joblib.load('Trained_model/scalers/scaler_AS.joblib')
BVP_Scaler = joblib.load('Trained_model/scalers/scaler_BVP.joblib')
CIC_Scaler = joblib.load('Trained_model/scalers/scaler_CIC.joblib')
CSI_Scaler = joblib.load('Trained_model/scalers/scaler_CSI.joblib')
ELISA_Scaler = joblib.load('Trained_model/scalers/scaler_ELISA.joblib')
HEK_Scaler = joblib.load('Trained_model/scalers/scaler_HEK.joblib')
HIC_Scaler = joblib.load('Trained_model/scalers/scaler_HIC.joblib')
PSR_Scaler = joblib.load('Trained_model/scalers/scaler_PSR.joblib')
SGAC_Scaler = joblib.load('Trained_model/scalers/scaler_SGAC.joblib')
SMAC_Scaler = joblib.load('Trained_model/scalers/scaler_SMAC.joblib')
Tm_Scaler = joblib.load('Trained_model/scalers/scaler_Tm.joblib')

/usr/local/lib/python3.12/dist-packages/sklearn/base.py:380: InconsistentVersionWarning: Trying to unpickle estimator StandardScaler from version 1.4.2 when using version 1.6.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

In [11]:
X_ACSINS = feature_ACSINS.values
X_AS = feature_AS.values
X_BVP = feature_BVP.values
X_CIC = feature_CIC.values
X_CSI = feature_CSI.values
X_ELISA = feature_ELISA.values
X_HIC = feature_HIC.values
X_HEK = feature_HEK.values
X_PSR = feature_PSR.values
X_SGAC = feature_SGAC.values
X_SMAC = feature_SMAC.values
X_Tm = feature_Tm.values

X_ACSINS = ACSINS_Scaler.transform(X_ACSINS)
X_AS = AS_Scaler.transform(X_AS)
X_BVP = BVP_Scaler.transform(X_BVP)
X_CIC = CIC_Scaler.transform(X_CIC)
X_CSI = CSI_Scaler.transform(X_CSI)
X_ELISA = ELISA_Scaler.transform(X_ELISA)
X_HIC = HIC_Scaler.transform(X_HIC)
X_HEK = HEK_Scaler.transform(X_HEK)
X_PSR = PSR_Scaler.transform(X_PSR)
X_SGAC = SGAC_Scaler.transform(X_SGAC)
X_SMAC = SMAC_Scaler.transform(X_SMAC)
X_Tm = Tm_Scaler.transform(X_Tm)

## Predictive Model Import

In [13]:
ACSINS_SVR_model = joblib.load('Trained_model/models/ACSINS_SVR_model.joblib')
AS_LR_model = joblib.load('Trained_model/models/AS_LR_model.joblib')
BVP_KNN_model = joblib.load('Trained_model/models/BVP_KNN_model.joblib')
CIC_KNN_model = joblib.load('Trained_model/models/CIC_KNN_model.joblib')
CSI_SVR_model = joblib.load('Trained_model/models/CSI_SVR_model.joblib')
ELISA_KNN_model = joblib.load('Trained_model/models/ELISA_KNN_model.joblib')
HEK_KNN_model = joblib.load('Trained_model/models/HEK_KNN_model.joblib')
HIC_SVR_model = joblib.load('Trained_model/models/HIC_SVR_model.joblib')
PSR_SVR_model = joblib.load('Trained_model/models/PSR_SVR_model.joblib')
SGAC_SVR_model = joblib.load('Trained_model/models/SGAC_SVR_model.joblib')
SMAC_KNN_model = joblib.load('Trained_model/models/SMAC_KNN_model.joblib')
Tm_KNN_model = joblib.load('Trained_model/models/Tm_KNN_model.joblib')

/usr/local/lib/python3.12/dist-packages/sklearn/base.py:380: InconsistentVersionWarning: Trying to unpickle estimator SVR from version 1.3.0 when using version 1.6.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/base.py:380: InconsistentVersionWarning: Trying to unpickle estimator LinearRegression from version 1.3.0 when using version 1.6.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/base.py:380: InconsistentVersionWarning: Trying to unpickle estimator KNeighborsRegressor from version 1.3.0 when using version 1.6.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

## Biophysical Properties Prediction

In [14]:
ACSINS_transformed,AS,BVP,CIC_transformed,CSI_transformed,ELISA,HIC,HEK,PSR,SGAC_transformed,SMAC_transformed,Tm =[],[],[],[],[],[],[],[],[],[],[],[]

for index,row in dataset_test.iterrows():

  feature_ACSINS = X_ACSINS[index]
  prediction_ACSINS = ACSINS_SVR_model.predict(feature_ACSINS.reshape(1,-1))
  feature_AS = X_AS[index]
  prediction_AS = AS_LR_model.predict(feature_AS.reshape(1,-1))
  feature_BVP = X_BVP[index]
  prediction_BVP = BVP_KNN_model.predict(feature_BVP.reshape(1,-1))
  feature_CIC = X_CIC[index]
  prediction_CIC = CIC_KNN_model.predict(feature_CIC.reshape(1,-1))
  feature_CSI = X_CSI[index]
  prediction_CSI = CSI_SVR_model.predict(feature_CSI.reshape(1,-1))
  feature_ELISA = X_ELISA[index]
  prediction_ELISA = ELISA_KNN_model.predict(feature_ELISA.reshape(1,-1))
  feature_HIC = X_HIC[index]
  prediction_HIC = HIC_SVR_model.predict(feature_HIC.reshape(1,-1))
  feature_HEK = X_HEK[index]
  prediction_HEK = HEK_KNN_model.predict(feature_HEK.reshape(1,-1))
  feature_PSR = X_PSR[index]
  prediction_PSR = PSR_SVR_model.predict(feature_PSR.reshape(1,-1))
  feature_SGAC = X_SGAC[index]
  prediction_SGAC = SGAC_SVR_model.predict(feature_SGAC.reshape(1,-1))
  feature_SMAC = X_SMAC[index]
  prediction_SMAC = SMAC_KNN_model.predict(feature_SMAC.reshape(1,-1))
  feature_Tm = X_Tm[index]
  prediction_Tm = Tm_KNN_model.predict(feature_Tm.reshape(1,-1))

  ACSINS_transformed.append(prediction_ACSINS)
  AS.append(prediction_AS)
  BVP.append(prediction_BVP)
  CIC_transformed.append(prediction_CIC)
  CSI_transformed.append(prediction_CSI)
  ELISA.append(prediction_ELISA)
  HIC.append(prediction_HIC)
  HEK.append(prediction_HEK)
  PSR.append(prediction_PSR)
  SGAC_transformed.append(prediction_SGAC)
  SMAC_transformed.append(prediction_SMAC)
  Tm.append(prediction_Tm)

## Result Sheet Generation

In [15]:
Name = dataset_test[['Name']].to_numpy()

In [16]:
data = np.column_stack((Name,ACSINS_transformed,AS,BVP,CIC_transformed,CSI_transformed,ELISA,HIC,HEK,PSR,SGAC_transformed,SMAC_transformed,Tm))

np.savetxt('Prediction_Result_anarcii.csv', data, delimiter=',', fmt='%s', header='Name,ACSINS_transformed,AS,BVP,CIC_transformed,CSI_transformed,ELISA,HIC,HEK,PSR,SGAC_transformed,SMAC_transformed,Tm', comments='')

In [17]:
Result = pd.read_csv('Prediction_Result.csv')
Result

,Name,ACSINS_transformed,AS,BVP,CIC_transformed,CSI_transformed,ELISA,HIC,HEK,PSR,SGAC_transformed,SMAC_transformed,Tm
0,abituzumab,0.129965,0.061849,2.241486,-0.150425,0.754456,1.246774,9.567307,110.547472,0.220896,0.066478,-0.609231,74.083333
1,abrilumab,-1.789201,0.031188,1.504088,-1.883633,-0.736264,1.098520,9.227625,133.475483,0.092503,0.498120,-0.504355,72.500000
2,adalimumab,-0.142208,0.050512,1.923480,0.332348,-0.007850,1.106229,9.436170,115.630949,0.078699,0.361446,-0.461127,72.333333
3,alemtuzumab,0.305071,0.073762,4.494636,-0.161054,0.165025,2.792832,9.446484,137.255561,0.144123,0.634713,-0.881810,68.916667
4,alirocumab,0.109300,0.047116,2.811663,-0.402932,-0.126657,1.150019,9.551408,120.915541,0.133017,0.352992,0.007217,75.416667
...,...,...,...,...,...,...,...,...,...,...,...,...,...
132,vedolizumab,-0.441513,0.052470,3.009651,-0.094506,-0.289167,1.204125,10.784502,156.510514,0.053686,0.158359,0.891792,74.416667
133,veltuzumab,0.563540,0.045539,1.557630,0.356199,-0.515231,1.065002,11.135058,183.962341,0.096939,0.422563,0.036602,69.750000
134,visilizumab,0.949517,0.052161,3.735838,0.133477,0.541219,1.580209,9.826037,219.159756,0.318070,-0.630253,-0.285582,69.916667
135,zalutumumab,-1.664908,0.036776,3.967388,-2.213117,-0.732720,1.155225,9.749339,175.253958,0.082598,0.617887,-0.233052,72.083333
136,zanolimumab,-0.155629,0.035442,1.972158,0.332507,0.199206,1.106626,9.600853,211.152890,0.071635,0.411648,-0.208343,75.333333